# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Disable deprecated member use warnings
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    # Disable unnecessary import info messages
    unnecessary_import: ignore

linter:
  rules:
    # Disable style-only lints that don't affect functionality
    unnecessary_library_name: false
    use_super_parameters: false
    sort_child_properties_last: false
    prefer_final_fields: false
    sized_box_for_whitespace: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
